# Generated by Django 5.0.6 on 2024-06-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_customuser_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_got_appointment',
            field=models.BooleanField(default=False),
        ),
    ]
