# Generated by Django 5.0.6 on 2024-06-14 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_customuser_is_got_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='passport_number',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='purpose_of_appointment',
            field=models.TextField(blank=True, help_text='Please describe the purpose of this appointment.'),
        ),
    ]
