# Generated by Django 5.0.6 on 2024-06-16 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_customuser_passport_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='purpose_of_appointment',
        ),
    ]
