# Generated by Django 5.0.6 on 2024-06-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_customuser_purpose_of_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='appointment_time',
            field=models.CharField(choices=[('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00')], default='09:00', max_length=5),
            preserve_default=False,
        ),
    ]
