# Generated by Django 5.0.6 on 2024-06-18 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_customuser_language_customuser_current_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='current_city',
            field=models.CharField(choices=[('Berlin', 'Berlin'), ('Hamburg', 'Hamburg'), ('Munich', 'Munich'), ('Cologne', 'Cologne'), ('Frankfurt', 'Frankfurt'), ('Stuttgart', 'Stuttgart'), ('Düsseldorf', 'Düsseldorf'), ('Dortmund', 'Dortmund'), ('Essen', 'Essen'), ('Leipzig', 'Leipzig'), ('Bremen', 'Bremen'), ('Dresden', 'Dresden'), ('Hanover', 'Hanover'), ('Nuremberg', 'Nuremberg'), ('Duisburg', 'Duisburg'), ('Bochum', 'Bochum'), ('Wuppertal', 'Wuppertal'), ('Bielefeld', 'Bielefeld'), ('Bonn', 'Bonn'), ('Münster', 'Münster'), ('Karlsruhe', 'Karlsruhe'), ('Mannheim', 'Mannheim'), ('Augsburg', 'Augsburg'), ('Wiesbaden', 'Wiesbaden'), ('Gelsenkirchen', 'Gelsenkirchen'), ('Mönchengladbach', 'Mönchengladbach'), ('Braunschweig', 'Braunschweig'), ('Chemnitz', 'Chemnitz'), ('Kiel', 'Kiel'), ('Aachen', 'Aachen'), ('Halle', 'Halle'), ('Magdeburg', 'Magdeburg'), ('Freiburg', 'Freiburg'), ('Krefeld', 'Krefeld'), ('Lübeck', 'Lübeck'), ('Oberhausen', 'Oberhausen'), ('Erfurt', 'Erfurt'), ('Mainz', 'Mainz'), ('Rostock', 'Rostock'), ('Kassel', 'Kassel'), ('Hagen', 'Hagen'), ('Saarbrücken', 'Saarbrücken'), ('Hamm', 'Hamm'), ('Mülheim', 'Mülheim'), ('Potsdam', 'Potsdam'), ('Ludwigshafen', 'Ludwigshafen'), ('Oldenburg', 'Oldenburg'), ('Leverkusen', 'Leverkusen'), ('Osnabrück', 'Osnabrück'), ('Solingen', 'Solingen'), ('Heidelberg', 'Heidelberg'), ('Herne', 'Herne'), ('Neuss', 'Neuss'), ('Darmstadt', 'Darmstadt'), ('Paderborn', 'Paderborn'), ('Regensburg', 'Regensburg'), ('Ingolstadt', 'Ingolstadt'), ('Würzburg', 'Würzburg'), ('Wolfsburg', 'Wolfsburg'), ('Offenbach', 'Offenbach'), ('Ulm', 'Ulm'), ('Heilbronn', 'Heilbronn'), ('Pforzheim', 'Pforzheim'), ('Göttingen', 'Göttingen'), ('Bottrop', 'Bottrop'), ('Trier', 'Trier'), ('Recklinghausen', 'Recklinghausen'), ('Reutlingen', 'Reutlingen'), ('Bremerhaven', 'Bremerhaven'), ('Koblenz', 'Koblenz'), ('Bergisch Gladbach', 'Bergisch Gladbach'), ('Jena', 'Jena'), ('Remscheid', 'Remscheid'), ('Erlangen', 'Erlangen'), ('Moers', 'Moers'), ('Siegen', 'Siegen'), ('Hildesheim', 'Hildesheim'), ('Salzgitter', 'Salzgitter')], help_text='Select your current city', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?[1-9]\\d{1,14}$')]),
        ),
    ]
