# Generated by Django 5.0.6 on 2024-06-20 01:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_customuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='appointment_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='appointment_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
