# Generated by Django 5.0.6 on 2024-06-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_customuser_appointment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
